### ISSUE TITLE
Porting to Firefox WebExtension

### ISSUE THREAD

**Issue by bost-ty** [daneden/chrome-lucid#8]
Hi Dan,

Mostly minor tweaks are needed in *manifest.json* and in *override.js* to work with Firefox.

I don't know how to note the changes in an issue (learning!), but I've uploaded the complete, semi-functional project to a repository at [https://github.com/bost-ty/firefox-lucid](https://github.com/bost-ty/firefox-lucid).

Hope this is helpful. The major issues I'm having still are noted in the Readme. I did update *override.css* to suit some preferences and some rough media queries (rough improvements for how I use the extension).

Primarily, something in Firefox causes an issue (maybe anti-fingerprinting or other privacy flags I have in place...) with local timezone and prefers-color-scheme. A small options menu might be a workaround to set those variables.

Hope the code is interesting!

--bost-ty

**Comment by bost-ty** [comment]
Submitted and accepted by Firefox! [Here's the page](https://addons.mozilla.org/en-US/firefox/addon/ff-lucid/) if anyone wants to try it or can solve the issues mentioned above.

**Comment by daneden** [comment]
Nice work @bost-ty! And thank you for sharing/credit :)
